"""empty message

Revision ID: bc8d42d12009
Revises: ce361f1b3d2c
Create Date: 2022-06-14 15:47:20.579455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc8d42d12009'
down_revision = 'ce361f1b3d2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建日期'))
    op.add_column('comment', sa.Column('is_deleted', sa.Integer(), nullable=True, comment='是否删除'))
    op.add_column('comment_up', sa.Column('is_deleted', sa.Integer(), nullable=True, comment='是否删除'))
    op.add_column('question', sa.Column('is_deleted', sa.Integer(), nullable=True, comment='是否删除'))
    op.add_column('question', sa.Column('category', sa.String(length=2000), nullable=True, comment='文章分类'))
    op.add_column('user', sa.Column('is_deleted', sa.Integer(), nullable=True, comment='是否删除'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_deleted')
    op.drop_column('question', 'category')
    op.drop_column('question', 'is_deleted')
    op.drop_column('comment_up', 'is_deleted')
    op.drop_column('comment', 'is_deleted')
    op.drop_column('category', 'create_time')
    # ### end Alembic commands ###
