"""empty message

Revision ID: ce361f1b3d2c
Revises: 
Create Date: 2022-06-14 15:39:22.944554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce361f1b3d2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_up',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('question_id', sa.BigInteger(), nullable=False, comment='问题ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('comment', 'user_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False,
               comment='用户ID')
    op.alter_column('comment', 'question_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False,
               comment='问题ID')
    op.alter_column('comment', 'content',
               existing_type=mysql.TEXT(),
               nullable=False,
               comment='内容')
    op.alter_column('comment', 'create_time',
               existing_type=mysql.DATETIME(),
               comment='创建日期',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建日期',
               existing_nullable=True)
    op.alter_column('comment', 'content',
               existing_type=mysql.TEXT(),
               nullable=True,
               comment=None,
               existing_comment='内容')
    op.alter_column('comment', 'question_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True,
               comment=None,
               existing_comment='问题ID')
    op.alter_column('comment', 'user_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True,
               comment=None,
               existing_comment='用户ID')
    op.drop_table('comment_up')
    op.drop_table('category')
    # ### end Alembic commands ###
